baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Chen Dongqi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: "Projects"
          url: projects/
          weight: 1
        - name: "Coursework"
          url: coursework/
          weight: 2
        - name: "About"
          url: about/
          weight: 3

params:
    description: "An undergraduate student majoring in Software Engineering at Fudan University. Passionate about software development and system design. Experienced in full-stack development, compiler design, and computer vision."
    author: "Chen Dongqi"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects", "coursework"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    
    profileMode:
        enabled: true
        title: "Chen Dongqi"
        subtitle: "Software Engineering Undergraduate at Fudan University"
        imageUrl: "avatar.jpg"
        imageWidth: 272
        imageHeight: 354
        buttons:
            - name: Projects
              url: projects/
            - name: Coursework
              url: coursework/
            
    socialIcons:
        - name: GitHub
          url: https://github.com/DqChen77
        - name: Email
          url: mailto:2091984032@qq.com

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2